apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: default
  annotations:
    nova.elotl.co/spread-onto: "${NOVA_WORKLOAD_CLUSTER_1},${NOVA_WORKLOAD_CLUSTER_2}::Duplicate"
  labels:
    app: busybox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox:stable
        command:
        - sleep
        - inf
