apiVersion: policy.elotl.co/v1alpha1
kind: SchedulePolicy
metadata:
  name: spread-group-policy
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: default
  groupBy:
    labelKey: app
  spreadConstraints:
    topologyKey: kubernetes.io/metadata.name
    percentageSplit:
    - topologyValue: ${NOVA_WORKLOAD_CLUSTER_1}
      percentage: 20
    - topologyValue: ${NOVA_WORKLOAD_CLUSTER_2}
      percentage: 80
  clusterSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - ${NOVA_WORKLOAD_CLUSTER_1}
      - ${NOVA_WORKLOAD_CLUSTER_2}
  resourceSelectors:
    labelSelectors:
    - matchLabels:
        group-policy: nginx-spread
