apiVersion: v1
kind: Secret
metadata:
  name: cluster1-pgbackrest-secrets
  labels:
    psql-cluster: all
type: Opaque
data:
  s3.conf: W2dsb2JhbF0KcmVwbzMtczMta2V5PW1pbmlvYWRtaW4KcmVwbzMtczMta2V5LXNlY3JldD1taW5pb2FkbWluCg==
