apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: v1
kind: Service
metadata:
  name: apiserver
  namespace: ${NAMESPACE}
  labels:
    component: apiserver
spec:
  type: LoadBalancer
  ports:
    - name: apiserver
      port: 443
      protocol: TCP
      targetPort: 6443
  selector:
    component: apiserver
