apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-controller-manager
  namespace: ${NAMESPACE}
  labels:
    component: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      component: controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: controller-manager
    spec:
      containers:
        - command:
            - kube-controller-manager
            # - --allocate-node-cidrs=true
            - --authentication-kubeconfig=/etc/nova/kubeconfig
            - --authorization-kubeconfig=/etc/nova/kubeconfig
            - --client-ca-file=/etc/kubernetes/pki/ca.crt
            - --controllers=garbagecollector,namespace,serviceaccount-token
            - --kubeconfig=/etc/nova/kubeconfig
            # - --leader-elect=true
            # - --node-cidr-mask-size=24
            # - --port=0
            - --root-ca-file=/etc/kubernetes/pki/ca.crt
            - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
            - --service-cluster-ip-range=10.96.0.0/16
            - --use-service-account-credentials=true
            - --v=2
          image: registry.k8s.io/kube-controller-manager:v1.21.7
          name: kube-controller-manager
          volumeMounts:
            - mountPath: /etc/kubernetes/pki
              name: nova-cert
              readOnly: true
            - mountPath: /etc/nova/
              name: nova-kubeconfig
              readOnly: true
      # priorityClassName: system-node-critical, GKE doesn't like system-node-critical pods in non kube-system namespace
      volumes:
        - name: nova-cert
          secret:
            secretName: nova-cert
        - name: nova-kubeconfig
          secret:
            secretName: nova-kubeconfig
