apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: ${NAMESPACE}
  labels:
    app: etcd
spec:
  # TODO: run an etcd cluster, the current deployment configuration doesn't support multiple etcd pods
  replicas: 1
  serviceName: etcd
  selector:
    matchLabels:
      app: etcd
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: registry.k8s.io/etcd:3.4.13-0
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -ec
                - 'etcdctl get /registry --prefix --keys-only  --endpoints https://127.0.0.1:2379  --cacert /etc/kubernetes/pki/etcd/ca.crt --cert /etc/kubernetes/pki/etcd/server.crt --key /etc/kubernetes/pki/etcd/server.key'
            failureThreshold: 2
            initialDelaySeconds: 120
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
          env:
            - name: ETCD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 2369
              name: client
              protocol: TCP
            - containerPort: 2370
              name: peer
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/etcd
              name: etcd-data
            - name: etcd-cert
              mountPath: /etc/kubernetes/pki/etcd
              readOnly: true
          command:
            - /usr/local/bin/etcd
            - --listen-peer-urls
            - http://0.0.0.0:2380
            - --listen-client-urls
            - https://0.0.0.0:2379
            - --advertise-client-urls
            - https://etcd-client.${NAMESPACE}.svc.cluster.local:2379
            - --initial-cluster-state
            - new
            - --cert-file=/etc/kubernetes/pki/etcd/server.crt
            - --client-cert-auth=true
            - --key-file=/etc/kubernetes/pki/etcd/server.key
            - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
            - --data-dir=/var/lib/etcd
      volumes:
        - name: etcd-cert
          secret:
            secretName: etcd-cert
  volumeClaimTemplates:
    - metadata:
        name: etcd-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
  name: etcd-client
  namespace: ${NAMESPACE}
spec:
  ports:
    - name: etcd-client
      port: 2379
      protocol: TCP
      targetPort: 2379
  selector:
    app: etcd
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
  name: etcd
  namespace: ${NAMESPACE}
spec:
  clusterIP: None
  ports:
    - name: client
      port: 2379
      protocol: TCP
      targetPort: 2379
    - name: peer
      port: 2380
      protocol: TCP
      targetPort: 2380
  selector:
    app: etcd
