apiVersion: v1
kind: Secret
metadata:
  name: nova-kubeconfig
  namespace: ${NAMESPACE}
stringData:
  kubeconfig: |-
    apiVersion: v1
    clusters:
      - cluster:
          certificate-authority: /etc/kubernetes/pki/ca.crt
          server: https://apiserver.${NAMESPACE}.svc.cluster.local
        name: local
    contexts:
      - context:
          cluster: local
          namespace: default
          user: user
        name: Default
    current-context: Default
    kind: Config
    preferences: {}
    users:
      - name: user
        user:
          client-certificate: /etc/kubernetes/pki/apiserver-client.crt
          client-key: /etc/kubernetes/pki/apiserver-client.key
