apiVersion: v1
kind: Secret
metadata:
  name: nova-cert
  namespace: ${NAMESPACE}
type: Opaque
data:
  front-proxy-ca.crt: $FRONT_PROXY_CA_CERT
  front-proxy-client.crt: $FRONT_PROXY_CLIENT_CERT
  front-proxy-client.key: $FRONT_PROXY_CLIENT_KEY
  ca.crt: $CA_CERT
  apiserver.crt: $APISERVER_CERT
  apiserver.key: $APISERVER_KEY
  apiserver-etcd-client.crt: $APISERVER_ETCD_CLIENT_CERT
  apiserver-etcd-client.key: $APISERVER_ETCD_CLIENT_KEY
  apiserver-client.crt: $APISERVER_CLIENT_CERT
  apiserver-client.key: $APISERVER_CLIENT_KEY
  sa.key: $SA_KEY
  sa.pub: $SA_PUB
