---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nova-scheduler
  namespace: ${NAMESPACE}
  labels:
    component: nova-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      component: nova-scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: nova-scheduler
    spec:
      containers:
        - name: scheduler
          image: ${IMAGE_REPO}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          env:
            - name: KUBECONFIG
              value: "/etc/nova/kubeconfig"
            - name: NOVA_IDLE_ENTER_STANDBY_ENABLE
              value: "${NOVA_IDLE_ENTER_STANDBY_ENABLE}"
            - name: NOVA_IDLE_ENTER_STANDBY_SECS
              value: "${NOVA_IDLE_ENTER_STANDBY_SECS}"
            - name: NOVA_DELETE_CLUSTER_IN_STANDBY
              value: "${NOVA_DELETE_CLUSTER_IN_STANDBY}"
            - name: NOVA_CREATE_CLUSTER_IF_NEEDED
              value: "${NOVA_CREATE_CLUSTER_IF_NEEDED}"
            - name: NOVA_MAX_CREATED_CLUSTERS
              value: "${NOVA_MAX_CREATED_CLUSTERS}"
            - name: AWS_ACCESS_KEY_ID
              value: "${AWS_ACCESS_KEY_ID}"
            - name: AWS_SECRET_ACCESS_KEY
              value: "${AWS_SECRET_ACCESS_KEY}"
            - name: GCE_ACCESS_KEY
              value: "${GCE_ACCESS_KEY}"
            - name: GCE_PROJECT_ID
              value: "${GCE_PROJECT_ID}"
            - name: AGENT_IMAGE_REPO
              value: "${AGENT_IMAGE_REPO}"
            - name: AGENT_IMAGE_TAG
              value: "${AGENT_IMAGE_TAG}"
            - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
              value: "/root/service-account.json"
            - name: KIND_HOST_ADDRESS
              value: "host.docker.internal"
          command:
            - /nova-scheduler
            - --v=3
          volumeMounts:
            - mountPath: /etc/kubernetes/pki
              name: nova-cert
              readOnly: true
            - mountPath: /etc/nova/
              name: nova-kubeconfig
              readOnly: true
      restartPolicy: Always
      imagePullSecrets:
      - name: elotl
      volumes:
        - name: nova-cert
          secret:
            secretName: nova-cert
        - name: nova-kubeconfig
          secret:
            secretName: nova-kubeconfig
