---
apiVersion: v1
kind: Namespace
metadata:
  name: elotl
---
apiVersion: v1
kind: Secret
metadata:
  name: nova-kubeconfig
  namespace: elotl
stringData:
  kubeconfig: |-
    apiVersion: v1
    clusters:
      - cluster:
          certificate-authority-data: ${CA_CERT}
          server: https://${APISERVER_PUBLIC_ENDPOINT}
        name: nova
    contexts:
      - context:
          cluster: nova
          user: nova-agent
        name: nova
    current-context: nova
    kind: Config
    preferences: {}
    users:
      - name: nova-agent
        user:
          client-certificate-data: ${APISERVER_CLIENT_CERT} 
          client-key-data: ${APISERVER_CLIENT_KEY}
