apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
  name: my-new-cron-object
  annotations:
     nova.elotl.co/cluster: kind-workload-1
spec:
  cronSpec: "* * * * */5"
  image: my-awesome-cron-image
  replicas: 2
