apiVersion: v1
kind: Pod
metadata:
  annotations:
    # update it with a name of the workload cluster in Nova control plane which you want to hog
    nova.elotl.co/cluster: ${NOVA_WORKLOAD_CLUSTER_2}
  labels:
    app: nginx
  namespace: default
  name: hog-pod
spec:
  containers:
    - image: busybox
      imagePullPolicy: IfNotPresent
      name: busybox
      command: [ "sleep" ]
      args: [ "inf" ]
      resources:
        requests:
          # Update cpu and memory with values that will occupy the most of your cluster resources
          cpu: 2000m
          memory: 250M
