apiVersion: v1
kind: Namespace
metadata:
  annotations:
    # this annotation tells Nova to create a copy of this namespace in each cluster
    # you can check tutorials/poc-spread-onto-multiple-clusters.md for more details about spread scheduling.
    # If your workload clusters are named differently, e.g. my-workload-cluster-1 & my-workload-cluster-2,
    # please change it to:
    # nova.elotl.co/spread-onto: "my-workload-cluster-1,my-workload-cluster-2::Duplicate"
    nova.elotl.co/spread-onto: "${NOVA_WORKLOAD_CLUSTER_1},${NOVA_WORKLOAD_CLUSTER_2}::Duplicate"
  name: nginx-group-demo
