apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
  name: my-new-cron-object
  annotations:
    # Edit me: please insert workload-cluster-unique-identifier here
    # nova.elotl.co/cluster: <workload-cluster-unique-identifier>
spec:
  cronSpec: "* * * * */5"
  image: my-awesome-cron-image
  replicas: 2
