apiVersion: policy.elotl.co/v1alpha1
kind: SchedulePolicy
metadata:
  name: app-guestbook
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: guestbook
  clusterSelector:
    matchLabels:
      kubernetes.io/metadata.name: ${NOVA_WORKLOAD_CLUSTER_1}  # change it to the name of one of your workload clusters
  resourceSelectors:
    labelSelectors:
      - matchLabels:
          app: redis
      - matchLabels:
          app: guestbook
